-- Plotwick — Supabase schema.
-- Paste this into the Supabase SQL editor (or run via `supabase db push`).
-- Safe to re-run: everything is idempotent.

-- ---------------------------------------------------------------------------
-- Stories (per-user saved games)
-- ---------------------------------------------------------------------------

-- Each row is one story; the full story object (history, chapters, cover…)
-- lives in `data` as jsonb, mirroring the client's localStorage shape.
create table if not exists public.stories (
  id text primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  data jsonb not null,
  title text,
  done boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.stories enable row level security;

-- Users can only see and touch their own stories.
drop policy if exists "own stories" on public.stories;
create policy "own stories" on public.stories
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create index if not exists stories_user_idx on public.stories (user_id, updated_at desc);

-- ---------------------------------------------------------------------------
-- Shared (published) stories: world-readable, written only by the server.
-- ---------------------------------------------------------------------------

create table if not exists public.shared_stories (
  id text primary key,
  user_id uuid references auth.users (id) on delete set null,
  data jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.shared_stories enable row level security;

drop policy if exists "anyone can read shares" on public.shared_stories;
create policy "anyone can read shares" on public.shared_stories
  for select
  using (true);
-- No insert/update/delete policies: only the service-role key (which bypasses
-- RLS) can write, i.e. the Plotwick server.

-- ---------------------------------------------------------------------------
-- Profiles & story credits
-- ---------------------------------------------------------------------------
-- One row per user, holding the cached Wick-credit balance. The immutable
-- credit_ledger below is the audit trail; this number is the fast read model.
-- A new signup receives exactly one complete Wick.
--
-- NOTE: the ledger reason 'welcome_novella' keeps its original spelling on
-- purpose. It is a stored enum value present in existing rows, so renaming it
-- would orphan history and break reconciliation. The reader-facing term is
-- "Wick"; this identifier is data, not copy.

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  credits integer not null default 1 check (credits >= 0),
  created_at timestamptz not null default now()
);
alter table public.profiles alter column credits set default 1;

alter table public.profiles enable row level security;

-- Users may READ their own balance. They may NOT write it — only the server
-- (via SECURITY DEFINER functions below) changes credits.
drop policy if exists "read own profile" on public.profiles;
create policy "read own profile" on public.profiles
  for select
  using (auth.uid() = id);

-- Every balance mutation has a globally unique idempotency key. Replaying a
-- webhook or retrying a story request therefore cannot change the balance
-- twice. balance_after makes reconciliation deterministic.
create table if not exists public.credit_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  delta integer not null check (delta <> 0),
  balance_after integer not null check (balance_after >= 0),
  reason text not null check (
    reason in (
      'opening_balance',
      'welcome_novella',
      'stripe_purchase',
      'story_start',
      'story_refund',
      'admin_adjustment'
    )
  ),
  idempotency_key text not null unique,
  story_id uuid,
  stripe_event_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.credit_ledger enable row level security;
create index if not exists credit_ledger_user_idx
  on public.credit_ledger (user_id, created_at desc);
create index if not exists credit_ledger_reason_idx
  on public.credit_ledger (reason, created_at desc);

-- Seed a reconciliation opening entry for accounts created before the ledger.
-- Their existing balance is intentionally preserved.
insert into public.credit_ledger (
  user_id, delta, balance_after, reason, idempotency_key,
  metadata
)
select
  p.id,
  p.credits,
  p.credits,
  'opening_balance',
  'opening:' || p.id::text,
  jsonb_build_object('migration', 'credit-ledger-v1')
from public.profiles p
where p.credits > 0
  and not exists (
    select 1 from public.credit_ledger l where l.user_id = p.id
  )
on conflict (idempotency_key) do nothing;

-- Auto-create a profile and its single welcome Wick atomically.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, credits) values (new.id, 1)
  on conflict (id) do nothing;
  insert into public.credit_ledger (
    user_id, delta, balance_after, reason, idempotency_key
  ) values (
    new.id, 1, 1, 'welcome_novella', 'welcome:' || new.id::text
  )
  on conflict (idempotency_key) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- One aggregate reconciliation pass for the staff dashboard. It compares each
-- cached profile balance with that reader's latest immutable ledger balance.
create or replace function public.credit_ledger_reconciliation()
returns table (
  profiles bigint,
  mismatches bigint,
  outstanding_credits bigint
)
language sql
security definer
set search_path = public
as $$
  select
    count(*)::bigint as profiles,
    count(*) filter (
      where p.credits <> coalesce(latest.balance_after, 0)
    )::bigint as mismatches,
    coalesce(sum(p.credits), 0)::bigint as outstanding_credits
  from public.profiles p
  left join lateral (
    select l.balance_after
    from public.credit_ledger l
    where l.user_id = p.id
    order by l.id desc
    limit 1
  ) latest on true;
$$;
revoke all on function public.credit_ledger_reconciliation()
  from public, anon, authenticated;

-- Lock and verify one reader's cached balance before any monetary mutation.
-- A mismatch fails closed and surfaces in operations instead of compounding.
create or replace function public.assert_credit_ledger_balance(p_user_id uuid)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_balance integer;
  v_ledger_balance integer;
begin
  select p.credits into v_profile_balance
    from public.profiles p
    where p.id = p_user_id
    for update;
  if not found then raise exception 'credit profile missing'; end if;

  select l.balance_after into v_ledger_balance
    from public.credit_ledger l
    where l.user_id = p_user_id
    order by l.id desc
    limit 1;
  v_ledger_balance := coalesce(v_ledger_balance, 0);
  if v_profile_balance <> v_ledger_balance then
    raise exception 'credit ledger mismatch';
  end if;
  return v_profile_balance;
end;
$$;
revoke all on function public.assert_credit_ledger_balance(uuid)
  from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Story-start charge ledger (anti-double-charge / idempotency)
-- ---------------------------------------------------------------------------
-- One row per story that has been charged. The first time the server generates
-- for a given story id, it inserts here and deducts a credit; later chapters of
-- the same story find the row already present and are free.

create table if not exists public.story_starts (
  story_id text primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  charged_at timestamptz not null default now()
);

alter table public.story_starts enable row level security;
-- No policies: server-only (service role) access.

-- Atomically "begin" a story: if this story id hasn't been charged yet, verify
-- the user has a credit, deduct one, and record the charge — all in one shot.
-- Returns the new balance and whether a credit was charged on this call.
-- Called only by the server via the service-role key.
create or replace function public.start_story(p_user_id uuid, p_story_id text)
returns table (ok boolean, charged boolean, credits integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_new_row integer;
  v_credits integer;
begin
  perform public.assert_credit_ledger_balance(p_user_id);
  -- Reserve the story id. If it already existed, this is a continuation.
  insert into public.story_starts (story_id, user_id)
  values (p_story_id, p_user_id)
  on conflict (story_id) do nothing;
  get diagnostics v_new_row = row_count;  -- 1 = we inserted, 0 = already charged

  if v_new_row = 0 then
    -- Legacy compatibility only: never let another user continue this id.
    if not exists (
      select 1 from public.story_starts
      where story_id = p_story_id and user_id = p_user_id
    ) then
      return query select false, false, 0;
      return;
    end if;
    select credits into v_credits from public.profiles where id = p_user_id;
    return query select true, false, coalesce(v_credits, 0);
    return;
  end if;

  -- New story: attempt to deduct one credit, locking the profile row.
  update public.profiles
    set credits = credits - 1
    where id = p_user_id and credits > 0
    returning credits into v_credits;

  if not found then
    -- No credits: undo the reservation so they can start once they top up.
    delete from public.story_starts where story_id = p_story_id;
    return query select false, false, 0;
    return;
  end if;

  insert into public.credit_ledger (
    user_id, delta, balance_after, reason, idempotency_key, metadata
  ) values (
    p_user_id,
    -1,
    v_credits,
    'story_start',
    'legacy-story:' || p_story_id || ':start',
    jsonb_build_object('legacy_story_id', p_story_id)
  );

  return query select true, true, v_credits;
end;
$$;

-- Undo a charge (used if the very first chapter fails to generate). Removes the
-- ledger row and refunds the credit so the user can retry cleanly.
create or replace function public.refund_story(p_user_id uuid, p_story_id text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_credits integer;
begin
  if exists (select 1 from public.story_starts
             where story_id = p_story_id and user_id = p_user_id) then
    perform public.assert_credit_ledger_balance(p_user_id);
    delete from public.story_starts where story_id = p_story_id;
    if not exists (
      select 1 from public.credit_ledger
      where idempotency_key = 'legacy-story:' || p_story_id || ':refund'
    ) then
      update public.profiles
        set credits = credits + 1
        where id = p_user_id
        returning credits into v_credits;
      insert into public.credit_ledger (
        user_id, delta, balance_after, reason, idempotency_key, metadata
      ) values (
        p_user_id,
        1,
        v_credits,
        'story_refund',
        'legacy-story:' || p_story_id || ':refund',
        jsonb_build_object('legacy_story_id', p_story_id)
      );
    end if;
  end if;
end;
$$;

-- ---------------------------------------------------------------------------
-- Stripe payments: idempotent credit grants
-- ---------------------------------------------------------------------------
-- Every processed Stripe event is recorded here so replays/retries never
-- double-grant credits.

create table if not exists public.stripe_events (
  id text primary key,               -- Stripe event id (evt_...)
  user_id uuid references auth.users (id) on delete set null,
  credits_granted integer not null,
  created_at timestamptz not null default now()
);

alter table public.stripe_events enable row level security;
-- Server-only (service role) access; no policies.

-- Grant credits for a paid Stripe event, exactly once. If the event id was
-- already processed, this is a no-op. Returns the new balance.
create or replace function public.grant_stripe_credits(
  p_event_id text, p_user_id uuid, p_credits integer)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_new_event integer;
  v_credits integer;
begin
  perform public.assert_credit_ledger_balance(p_user_id);
  insert into public.stripe_events (id, user_id, credits_granted)
  values (p_event_id, p_user_id, p_credits)
  on conflict (id) do nothing;
  get diagnostics v_new_event = row_count;

  if v_new_event = 0 then
    -- Already processed this event; return current balance unchanged.
    select credits into v_credits from public.profiles where id = p_user_id;
    return coalesce(v_credits, 0);
  end if;

  insert into public.profiles (id, credits) values (p_user_id, p_credits)
  on conflict (id) do update set credits = public.profiles.credits + p_credits
  returning credits into v_credits;

  insert into public.credit_ledger (
    user_id, delta, balance_after, reason, idempotency_key,
    stripe_event_id, metadata
  ) values (
    p_user_id,
    p_credits,
    v_credits,
    'stripe_purchase',
    'stripe:' || p_event_id,
    p_event_id,
    jsonb_build_object('legacy_grant', true)
  );

  return v_credits;
end;
$$;

-- Lock all three money functions down: they run as SECURITY DEFINER, so make
-- sure end users (anon / authenticated) can NEVER call them directly. Only the
-- server's service-role key (which bypasses these grants) may invoke them.
revoke all on function public.start_story(uuid, text) from public, anon, authenticated;
revoke all on function public.refund_story(uuid, text) from public, anon, authenticated;
revoke all on function public.grant_stripe_credits(text, uuid, integer) from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Authoritative story sessions
-- ---------------------------------------------------------------------------
-- The browser still carries full story history for generation, but it may not
-- invent continuations. The server stores only integrity metadata: owner,
-- immutable scenario/character hashes, and a rolling hash of completed history.

create table if not exists public.story_sessions (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  scenario_hash text not null,
  character_hash text not null,
  history_hash text,
  chapter_count integer not null default 0 check (chapter_count >= 0),
  status text not null default 'generating' check (status in ('ready', 'generating')),
  active_request_id uuid,
  start_token uuid,
  charged boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.story_sessions enable row level security;
alter table public.story_sessions add column if not exists start_token uuid;
create index if not exists story_sessions_user_idx
  on public.story_sessions (user_id, updated_at desc);
create unique index if not exists story_sessions_start_token_idx
  on public.story_sessions (user_id, start_token)
  where start_token is not null;

create or replace function public.begin_story_session(
  p_user_id uuid,
  p_story_id uuid,
  p_scenario_hash text,
  p_character_hash text,
  p_request_id uuid,
  p_charge boolean
)
returns table (ok boolean, charged boolean, credits integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_credits integer;
begin
  if p_charge then
    perform public.assert_credit_ledger_balance(p_user_id);
    update public.profiles
      set credits = credits - 1
      where id = p_user_id and credits > 0
      returning profiles.credits into v_credits;
    if not found then
      return query select false, false, 0;
      return;
    end if;
    insert into public.credit_ledger (
      user_id, delta, balance_after, reason, idempotency_key, story_id
    ) values (
      p_user_id,
      -1,
      v_credits,
      'story_start',
      'story:' || p_story_id::text || ':start',
      p_story_id
    );
  else
    select profiles.credits into v_credits
      from public.profiles where id = p_user_id;
  end if;

  insert into public.story_sessions (
    id, user_id, scenario_hash, character_hash, status,
    active_request_id, charged
  ) values (
    p_story_id, p_user_id, p_scenario_hash, p_character_hash, 'generating',
    p_request_id, p_charge
  );

  if p_charge then
    insert into public.story_starts (story_id, user_id)
      values (p_story_id::text, p_user_id);
  end if;
  return query select true, p_charge, coalesce(v_credits, 0);
end;
$$;

create or replace function public.claim_story_chapter(
  p_user_id uuid,
  p_story_id uuid,
  p_scenario_hash text,
  p_character_hash text,
  p_prior_history_hash text,
  p_request_id uuid
)
returns table (ok boolean, conflict boolean, credits integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_credits integer;
begin
  select profiles.credits into v_credits
    from public.profiles where id = p_user_id;

  update public.story_sessions
    set status = 'generating',
        active_request_id = p_request_id,
        updated_at = now()
    where id = p_story_id
      and user_id = p_user_id
      and scenario_hash = p_scenario_hash
      and character_hash = p_character_hash
      and history_hash = p_prior_history_hash
      and (
        status = 'ready'
        or (status = 'generating' and updated_at < now() - interval '5 minutes')
      );
  if found then
    return query select true, false, coalesce(v_credits, 0);
  else
    return query select false, true, coalesce(v_credits, 0);
  end if;
end;
$$;

create or replace function public.complete_story_chapter(
  p_user_id uuid,
  p_story_id uuid,
  p_request_id uuid,
  p_history_hash text,
  p_chapter_count integer
)
returns table (ok boolean)
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.story_sessions
    set history_hash = p_history_hash,
        chapter_count = p_chapter_count,
        status = 'ready',
        active_request_id = null,
        updated_at = now()
    where id = p_story_id
      and user_id = p_user_id
      and status = 'generating'
      and active_request_id = p_request_id
      and p_chapter_count = chapter_count + 1;
  return query select found;
end;
$$;

create or replace function public.fail_story_chapter(
  p_user_id uuid,
  p_story_id uuid,
  p_request_id uuid
)
returns table (reset boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session public.story_sessions%rowtype;
  v_credits integer;
begin
  select * into v_session
    from public.story_sessions
    where id = p_story_id
      and user_id = p_user_id
      and active_request_id = p_request_id
    for update;
  if not found then
    return query select false;
    return;
  end if;

  if v_session.chapter_count = 0 then
    delete from public.story_sessions where id = p_story_id;
    if v_session.charged then
      perform public.assert_credit_ledger_balance(p_user_id);
      delete from public.story_starts
        where story_id = p_story_id::text and user_id = p_user_id;
      if exists (
        select 1 from public.credit_ledger
        where idempotency_key = 'story:' || p_story_id::text || ':start'
          and user_id = p_user_id
      ) and not exists (
        select 1 from public.credit_ledger
        where idempotency_key = 'story:' || p_story_id::text || ':refund'
          and user_id = p_user_id
      ) then
        update public.profiles
          set credits = credits + 1
          where id = p_user_id
          returning profiles.credits into v_credits;
        insert into public.credit_ledger (
          user_id, delta, balance_after, reason, idempotency_key, story_id
        ) values (
          p_user_id,
          1,
          v_credits,
          'story_refund',
          'story:' || p_story_id::text || ':refund',
          p_story_id
        );
      end if;
    end if;
    return query select true;
  else
    update public.story_sessions
      set status = 'ready', active_request_id = null, updated_at = now()
      where id = p_story_id;
    return query select false;
  end if;
end;
$$;

revoke all on function public.begin_story_session(uuid, uuid, text, text, uuid, boolean)
  from public, anon, authenticated;
revoke all on function public.claim_story_chapter(uuid, uuid, text, text, text, uuid)
  from public, anon, authenticated;
revoke all on function public.complete_story_chapter(uuid, uuid, uuid, text, integer)
  from public, anon, authenticated;
revoke all on function public.fail_story_chapter(uuid, uuid, uuid)
  from public, anon, authenticated;

-- A first chapter carries a stable client start token. Two simultaneous
-- requests for the same click can no longer create or charge two stories.
-- Keep the original function above during rolling deploys; the server uses v2.
create or replace function public.begin_story_session_v2(
  p_user_id uuid,
  p_story_id uuid,
  p_scenario_hash text,
  p_character_hash text,
  p_request_id uuid,
  p_start_token uuid,
  p_charge boolean
)
returns table (ok boolean, charged boolean, credits integer, conflict boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_credits integer;
begin
  insert into public.story_sessions (
    id, user_id, scenario_hash, character_hash, status,
    active_request_id, start_token, charged
  ) values (
    p_story_id, p_user_id, p_scenario_hash, p_character_hash, 'generating',
    p_request_id, p_start_token, p_charge
  )
  on conflict (user_id, start_token) where start_token is not null do nothing;

  if not found then
    select profiles.credits into v_credits
      from public.profiles where id = p_user_id;
    return query select false, false, coalesce(v_credits, 0), true;
    return;
  end if;

  if p_charge then
    perform public.assert_credit_ledger_balance(p_user_id);
    update public.profiles
      set credits = profiles.credits - 1
      where id = p_user_id and profiles.credits > 0
      returning profiles.credits into v_credits;
    if not found then
      delete from public.story_sessions
        where id = p_story_id and active_request_id = p_request_id;
      return query select false, false, 0, false;
      return;
    end if;
    insert into public.credit_ledger (
      user_id, delta, balance_after, reason, idempotency_key, story_id
    ) values (
      p_user_id,
      -1,
      v_credits,
      'story_start',
      'story:' || p_story_id::text || ':start',
      p_story_id
    );
    insert into public.story_starts (story_id, user_id)
      values (p_story_id::text, p_user_id);
  else
    select profiles.credits into v_credits
      from public.profiles where id = p_user_id;
  end if;

  return query select true, p_charge, coalesce(v_credits, 0), false;
end;
$$;

revoke all on function public.begin_story_session_v2(
  uuid, uuid, text, text, uuid, uuid, boolean
) from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Adopt an anonymous teaser chapter into a real, owned story.
--
-- A teaser is chapter one generated for a visitor with no account: no session,
-- no ledger entry, no charge. When they sign in to keep reading, this turns that
-- chapter into an ordinary story session and takes the Wick. From here on the
-- story is indistinguishable from one begun the normal way, so claim_story_chapter
-- and the reconciliation views need no special cases.
--
-- Two details matter and are easy to get wrong:
--
--   * history_hash is seeded to the hash of [opening, chapter] — exactly what
--     complete_story_chapter would have written after a normal chapter one — so
--     the very next claim_story_chapter call matches.
--
--   * chapter_count stays 0, NOT 1. It counts chapters delivered *under the
--     charge*, and the teaser chapter was free. fail_story_chapter only refunds
--     when chapter_count = 0, so seeding 1 here would silently swallow the Wick
--     when the reader's first paid chapter fails.
-- ---------------------------------------------------------------------------
create or replace function public.adopt_teaser_session(
  p_user_id uuid,
  p_story_id uuid,
  p_scenario_hash text,
  p_character_hash text,
  p_history_hash text,
  p_start_token uuid,
  p_charge boolean
)
returns table (ok boolean, charged boolean, credits integer, conflict boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_credits integer;
begin
  insert into public.story_sessions (
    id, user_id, scenario_hash, character_hash, history_hash,
    chapter_count, status, active_request_id, start_token, charged
  ) values (
    p_story_id, p_user_id, p_scenario_hash, p_character_hash, p_history_hash,
    0, 'ready', null, p_start_token, p_charge
  )
  on conflict (user_id, start_token) where start_token is not null do nothing;

  if not found then
    select profiles.credits into v_credits
      from public.profiles where id = p_user_id;
    return query select false, false, coalesce(v_credits, 0), true;
    return;
  end if;

  if p_charge then
    perform public.assert_credit_ledger_balance(p_user_id);
    update public.profiles
      set credits = profiles.credits - 1
      where id = p_user_id and profiles.credits > 0
      returning profiles.credits into v_credits;
    if not found then
      delete from public.story_sessions
        where id = p_story_id and user_id = p_user_id;
      return query select false, false, 0, false;
      return;
    end if;
    insert into public.credit_ledger (
      user_id, delta, balance_after, reason, idempotency_key, story_id
    ) values (
      p_user_id,
      -1,
      v_credits,
      'story_start',
      'story:' || p_story_id::text || ':start',
      p_story_id
    );
    insert into public.story_starts (story_id, user_id)
      values (p_story_id::text, p_user_id);
  else
    select profiles.credits into v_credits
      from public.profiles where id = p_user_id;
  end if;

  return query select true, p_charge, coalesce(v_credits, 0), false;
end;
$$;

revoke all on function public.adopt_teaser_session(
  uuid, uuid, text, text, text, uuid, boolean
) from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Distributed rate limits and operational usage
-- ---------------------------------------------------------------------------

create table if not exists public.rate_limit_buckets (
  key text not null,
  bucket bigint not null,
  count integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (key, bucket)
);
alter table public.rate_limit_buckets enable row level security;

create or replace function public.consume_rate_limit(
  p_key text, p_limit integer, p_window_seconds integer
)
returns table (allowed boolean, remaining integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_bucket bigint;
  v_count integer;
begin
  if p_limit < 1 or p_window_seconds < 1 then
    return query select false, 0;
    return;
  end if;
  v_bucket := floor(extract(epoch from now()) / p_window_seconds);
  insert into public.rate_limit_buckets (key, bucket, count)
    values (p_key, v_bucket, 1)
    on conflict (key, bucket)
    do update set count = public.rate_limit_buckets.count + 1, updated_at = now()
    returning count into v_count;
  return query select v_count <= p_limit, greatest(p_limit - v_count, 0);
end;
$$;
revoke all on function public.consume_rate_limit(text, integer, integer)
  from public, anon, authenticated;

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  request_id text,
  user_id uuid references auth.users (id) on delete set null,
  story_id text,
  kind text not null,
  model text not null,
  input_tokens integer not null default 0,
  output_tokens integer not null default 0,
  estimated_cost_micros bigint not null default 0 check (estimated_cost_micros >= 0),
  status text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.usage_events
  add column if not exists estimated_cost_micros bigint not null default 0;
alter table public.usage_events enable row level security;
create index if not exists usage_events_created_idx on public.usage_events (created_at desc);
create index if not exists usage_events_user_idx on public.usage_events (user_id, created_at desc);

-- Privacy-minimized product analytics. actor_key is either a user-scoped key
-- or a salted hash of a browser-generated anonymous session id; raw visitor
-- identifiers and story text are never stored.
create table if not exists public.product_events (
  id uuid primary key,
  actor_key text not null,
  user_id uuid references auth.users (id) on delete set null,
  event text not null check (
    event in (
      'world_selected',
      'setup_completed',
      'story_started',
      'story_completed',
      'checkout_opened',
      'purchase_completed'
    )
  ),
  world_id text,
  story_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.product_events enable row level security;
create index if not exists product_events_created_idx
  on public.product_events (created_at desc);
create index if not exists product_events_event_idx
  on public.product_events (event, created_at desc);
create index if not exists product_events_actor_idx
  on public.product_events (actor_key, created_at desc);

create table if not exists public.share_reports (
  id bigint generated by default as identity primary key,
  share_id text not null references public.shared_stories (id) on delete cascade,
  reason text not null,
  reporter_hash text not null,
  status text not null default 'open',
  created_at timestamptz not null default now()
);
alter table public.share_reports enable row level security;
create index if not exists share_reports_status_idx on public.share_reports (status, created_at desc);

-- Store enough purchase context to reconcile paid sessions from Stripe.
alter table public.stripe_events add column if not exists session_id text;
alter table public.stripe_events add column if not exists pack_id text;
alter table public.stripe_events add column if not exists amount_total integer;
alter table public.stripe_events add column if not exists currency text;
alter table public.stripe_events add column if not exists payment_intent text;
alter table public.stripe_events add column if not exists refunded_at timestamptz;
create unique index if not exists stripe_events_payment_intent_idx
  on public.stripe_events (payment_intent)
  where payment_intent is not null;

alter table public.credit_ledger
  drop constraint if exists credit_ledger_reason_check;
alter table public.credit_ledger
  add constraint credit_ledger_reason_check check (
    reason in (
      'opening_balance',
      'welcome_novella',
      'stripe_purchase',
      'stripe_refund',
      'story_start',
      'story_refund',
      'admin_adjustment'
    )
  );

create table if not exists public.stripe_refunds (
  id text primary key,
  payment_intent text not null,
  purchase_event_id text references public.stripe_events (id) on delete set null,
  user_id uuid references auth.users (id) on delete set null,
  amount_refunded integer not null check (amount_refunded > 0),
  currency text not null,
  credits_revoked integer not null default 0 check (credits_revoked >= 0),
  created_at timestamptz not null default now()
);
alter table public.stripe_refunds enable row level security;
create index if not exists stripe_refunds_payment_intent_idx
  on public.stripe_refunds (payment_intent, created_at desc);

create or replace function public.grant_stripe_credits(
  p_event_id text,
  p_user_id uuid,
  p_credits integer,
  p_session_id text,
  p_pack_id text,
  p_payment_intent text,
  p_amount_total integer,
  p_currency text
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_new_event integer;
  v_credits integer;
begin
  if p_credits <= 0 then raise exception 'invalid credit grant'; end if;
  if p_amount_total <= 0 then raise exception 'invalid purchase amount'; end if;
  perform public.assert_credit_ledger_balance(p_user_id);
  insert into public.stripe_events (
    id, user_id, credits_granted, session_id, pack_id, payment_intent,
    amount_total, currency
  ) values (
    p_event_id, p_user_id, p_credits, p_session_id, p_pack_id, p_payment_intent,
    p_amount_total, lower(p_currency)
  ) on conflict (id) do nothing;
  get diagnostics v_new_event = row_count;
  if v_new_event = 0 then
    select profiles.credits into v_credits
      from public.profiles where id = p_user_id;
    return coalesce(v_credits, 0);
  end if;
  insert into public.profiles (id, credits) values (p_user_id, p_credits)
  on conflict (id) do update
    set credits = public.profiles.credits + p_credits
  returning profiles.credits into v_credits;
  insert into public.credit_ledger (
    user_id,
    delta,
    balance_after,
    reason,
    idempotency_key,
    stripe_event_id,
    metadata
  ) values (
    p_user_id,
    p_credits,
    v_credits,
    'stripe_purchase',
    'stripe:' || p_event_id,
    p_event_id,
    jsonb_build_object(
      'session_id', p_session_id,
      'pack_id', p_pack_id,
      'payment_intent', p_payment_intent,
      'amount_total', p_amount_total,
      'currency', lower(p_currency)
    )
  );
  return v_credits;
end;
$$;
revoke all on function public.grant_stripe_credits(
  text, uuid, integer, text, text, text, integer, text
)
  from public, anon, authenticated;

create or replace function public.refund_stripe_credits(
  p_event_id text,
  p_payment_intent text,
  p_amount_refunded integer,
  p_currency text
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_purchase public.stripe_events%rowtype;
  v_current_credits integer;
  v_revoke integer;
  v_new_refund integer;
begin
  if coalesce(p_event_id, '') = '' then raise exception 'missing refund event'; end if;
  if coalesce(p_payment_intent, '') = '' then raise exception 'missing payment intent'; end if;
  if p_amount_refunded <= 0 then raise exception 'invalid refund amount'; end if;

  select * into v_purchase
    from public.stripe_events
    where payment_intent = p_payment_intent
    for update;
  if not found then raise exception 'purchase not found for payment intent'; end if;
  if lower(p_currency) <> lower(v_purchase.currency) then
    raise exception 'refund currency mismatch';
  end if;
  if p_amount_refunded < v_purchase.amount_total then
    raise exception 'partial refunds require manual credit review';
  end if;

  insert into public.stripe_refunds (
    id, payment_intent, purchase_event_id, user_id,
    amount_refunded, currency, credits_revoked
  ) values (
    p_event_id, p_payment_intent, v_purchase.id, v_purchase.user_id,
    p_amount_refunded, lower(p_currency), 0
  ) on conflict (id) do nothing;
  get diagnostics v_new_refund = row_count;

  select credits into v_current_credits
    from public.profiles
    where id = v_purchase.user_id
    for update;
  v_current_credits := coalesce(v_current_credits, 0);
  if v_new_refund = 0 or v_purchase.refunded_at is not null then
    return v_current_credits;
  end if;

  perform public.assert_credit_ledger_balance(v_purchase.user_id);
  v_revoke := least(v_current_credits, v_purchase.credits_granted);
  if v_revoke > 0 then
    update public.profiles
      set credits = credits - v_revoke
      where id = v_purchase.user_id
      returning credits into v_current_credits;
    insert into public.credit_ledger (
      user_id, delta, balance_after, reason, idempotency_key,
      stripe_event_id, metadata
    ) values (
      v_purchase.user_id,
      -v_revoke,
      v_current_credits,
      'stripe_refund',
      'stripe-refund:' || p_event_id,
      p_event_id,
      jsonb_build_object(
        'purchase_event_id', v_purchase.id,
        'payment_intent', p_payment_intent,
        'amount_refunded', p_amount_refunded,
        'currency', lower(p_currency),
        'unspent_credits_revoked', v_revoke
      )
    );
  end if;
  update public.stripe_refunds
    set credits_revoked = v_revoke
    where id = p_event_id;
  update public.stripe_events
    set refunded_at = now()
    where id = v_purchase.id;
  return v_current_credits;
end;
$$;
revoke all on function public.refund_stripe_credits(
  text, text, integer, text
)
  from public, anon, authenticated;

-- Rolling-deploy compatibility: an older server may briefly call the previous
-- five-argument RPC after this schema is installed. It still receives the same
-- idempotency and ledger guarantees; only revenue metadata is unavailable.
create or replace function public.grant_stripe_credits(
  p_event_id text,
  p_user_id uuid,
  p_credits integer,
  p_session_id text,
  p_pack_id text
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_new_event integer;
  v_credits integer;
begin
  if p_credits <= 0 then raise exception 'invalid credit grant'; end if;
  perform public.assert_credit_ledger_balance(p_user_id);
  insert into public.stripe_events (
    id, user_id, credits_granted, session_id, pack_id
  ) values (
    p_event_id, p_user_id, p_credits, p_session_id, p_pack_id
  ) on conflict (id) do nothing;
  get diagnostics v_new_event = row_count;
  if v_new_event = 0 then
    select profiles.credits into v_credits
      from public.profiles where id = p_user_id;
    return coalesce(v_credits, 0);
  end if;
  insert into public.profiles (id, credits) values (p_user_id, p_credits)
  on conflict (id) do update
    set credits = public.profiles.credits + p_credits
  returning profiles.credits into v_credits;
  insert into public.credit_ledger (
    user_id, delta, balance_after, reason, idempotency_key,
    stripe_event_id, metadata
  ) values (
    p_user_id,
    p_credits,
    v_credits,
    'stripe_purchase',
    'stripe:' || p_event_id,
    p_event_id,
    jsonb_build_object(
      'session_id', p_session_id,
      'pack_id', p_pack_id,
      'rolling_deploy_compatibility', true
    )
  );
  return v_credits;
end;
$$;
revoke all on function public.grant_stripe_credits(
  text, uuid, integer, text, text
)
  from public, anon, authenticated;
