"use strict";

// GENERATED by tools/build-worlds.js — do not edit by hand.
// Regenerate with: node tools/build-worlds.js
//
// The allowlist of built-in scenarios, as hashes of the { title, premise, tone }
// triple the client sends. Anonymous teaser chapters are restricted to these:
// without the restriction, an unauthenticated visitor could put an arbitrary
// premise in front of the model on our API key.
//
// Titles are kept alongside the hashes for readability only; nothing matches on
// them. test/worlds.test.js fails if these fall out of sync with public/app.js.

const BUILTIN_SCENARIOS = {
  "fantasy": [
    { title: "The Shattered Crown", hash: "de83adc6f346e75ce6295a52ef67883b6ab63d0ed8257e2cd4c84444879a4e6d" },
    { title: "The Witchglass Road", hash: "89bd5a270c79800634cd3091aaab7721d61882d2993af976057145be32e9a360" },
    { title: "The Drowned God's Bargain", hash: "0732de6de41301455eeeb4246b34a736a5cfbd9e73a20f0d429f95e72990a569" },
  ],
  "scifi": [
    { title: "Signal from Europa", hash: "6f43e5cdbe2e82c41608c5ad3fa8daa362ce936197a92068837d0f301d524987" },
    { title: "The Ninth Passenger", hash: "8ba56ac0ba312bc2634d39fedbb4130f2afedcf4a3d6826cf925f1df4d484720" },
    { title: "The Ares Silence", hash: "31624ac91525c60efe679299b847ddf85a761cab26eea79111a56b124ed76915" },
  ],
  "mystery": [
    { title: "The Glass House Murders", hash: "df466b5e8168d854de71d596d57a34bd525b6291c43b48f27d9fac97b8599e60" },
    { title: "The Last Curtain", hash: "5993cee9d8128907931b8b611fe8e81e8eeb9d2aed0de1e0cbdf54f12f208c97" },
    { title: "Table for Seven", hash: "b5fe941d8a46987ce53dd062f37f3cbd2bba105fa45c330fba4c676d7154224f" },
  ],
  "horror": [
    { title: "The Hollow Below", hash: "3ff2002e36691172f8714dc9e07fae6343d551b9b4939f58cf7cfcd999d685ce" },
    { title: "The Well-Behaved", hash: "b490df0b97046de06bf704b1a165ac0e23052fd9f71c130145cf8ba9cddec0dc" },
    { title: "Saltmarsh", hash: "5910ffc3663ff74bdbcfcc0911a114a01c1dc368777cb741b23beab96f5881f5" },
  ],
  "western": [
    { title: "Red Dust Reckoning", hash: "6577b174249114f668e037a59389c246415d9f83cb951622bfca7b689553e831" },
    { title: "The Hanging Tree", hash: "4f5ea201f741ea13d53b7653f8efb75e7f53452686bb621542d17f8517fe32a2" },
    { title: "The Silver Widow", hash: "b470961f1a2e7a5a9d5c707e22910e696eb418af3687e42558cb8a771a51b44b" },
  ],
  "romance": [
    { title: "A Season of Masks", hash: "871e9cb079acc669769d17a2f479b8bb07b853ffb60d5155409bc1e984fd907e" },
    { title: "The Sunset Clause", hash: "2f9cd91f2cdfb2096ddc3be778b2b93d7a7d7b6bec13cf8a1516a8284b106e78" },
    { title: "The Enemy's Garden", hash: "0035b281644347e15eb10b10aa4e40cc8a2596b9fb321242555dcfb5bffe891a" },
  ],
};

const BUILTIN_HASHES = new Set(
  Object.values(BUILTIN_SCENARIOS).flatMap((stories) => stories.map((s) => s.hash)),
);

function isBuiltinWorld(worldId) {
  return typeof worldId === "string" && Object.hasOwn(BUILTIN_SCENARIOS, worldId);
}

// True only when worldId names a built-in world AND the scenario is one of that
// world's stories. Both halves matter: the world id alone is client-supplied and
// says nothing about the premise travelling with it.
function isBuiltinScenario(worldId, scenarioHash) {
  if (!isBuiltinWorld(worldId)) return false;
  return BUILTIN_SCENARIOS[worldId].some((s) => s.hash === scenarioHash);
}

module.exports = {
  BUILTIN_SCENARIOS,
  BUILTIN_HASHES,
  isBuiltinWorld,
  isBuiltinScenario,
};
