"use strict";

// Regenerates lib/worlds.js — the server-side allowlist of built-in scenarios.
//
// The world catalogue lives in public/app.js because the browser needs the full
// cast (names, archetypes, traits, ornaments). The server only needs to answer
// one question: "is this scenario one of ours?" — which it does by hashing the
// {title, premise, tone} triple the client actually sends.
//
// This script reads that catalogue and writes the hashes to lib/worlds.js. The
// server never parses public/app.js at runtime; it loads the generated file.
// test/worlds.test.js re-runs this extraction and fails if the two drift.
//
//   node tools/build-worlds.js        # rewrite lib/worlds.js
//
// Run it whenever a built-in world's title, premise, or tone changes.

const fs = require("fs");
const path = require("path");
const { hashValue } = require("../lib/core");

const ROOT = path.join(__dirname, "..");
const APP_JS = path.join(ROOT, "public", "app.js");
const OUT = path.join(ROOT, "lib", "worlds.js");
const CATALOG_OUT = path.join(ROOT, "lib", "builtin-catalog.json");

// Pull the SCENARIOS array literal out of the frontend bundle and evaluate it.
// It is pure data, and this only ever runs as a build step — never in the
// server process.
function extractCatalogue(source) {
  const marker = "const SCENARIOS = ";
  const start = source.indexOf(marker);
  if (start === -1) throw new Error("could not find `const SCENARIOS =` in public/app.js");
  const end = source.indexOf("\n];", start);
  if (end === -1) throw new Error("could not find the end of the SCENARIOS array");
  const literal = source.slice(start + marker.length, end + 2);
  // eslint-disable-next-line no-new-func
  return new Function(`return (${literal});`)();
}

// The client sends { title, premise, tone } (public/app.js buildScenario), and
// the server trims each field via cleanStoryInputs before hashing. Mirror that
// exactly or the hashes will not match at runtime.
function scenarioTriple(world, story) {
  return {
    title: String(story.title).trim(),
    premise: String(story.premise).trim(),
    tone: String(story.tone || world.tone).trim(),
  };
}

function extractBuiltins(source) {
  const catalogue = extractCatalogue(source || fs.readFileSync(APP_JS, "utf8"));
  const worlds = {};
  for (const world of catalogue) {
    if (!world || !world.id || !Array.isArray(world.stories)) continue;
    worlds[world.id] = world.stories.map((story) => {
      const triple = scenarioTriple(world, story);
      return { title: triple.title, hash: hashValue(triple) };
    });
  }
  return worlds;
}

function render(worlds) {
  const entries = Object.entries(worlds)
    .map(([id, stories]) => {
      const lines = stories
        .map((s) => `    { title: ${JSON.stringify(s.title)}, hash: "${s.hash}" },`)
        .join("\n");
      return `  ${JSON.stringify(id)}: [\n${lines}\n  ],`;
    })
    .join("\n");

  return `"use strict";

// GENERATED by tools/build-worlds.js — do not edit by hand.
// Regenerate with: node tools/build-worlds.js
//
// The allowlist of built-in scenarios, as hashes of the { title, premise, tone }
// triple the client sends. Anonymous teaser chapters are restricted to these:
// without the restriction, an unauthenticated visitor could put an arbitrary
// premise in front of the model on our API key.
//
// Titles are kept alongside the hashes for readability only; nothing matches on
// them. test/worlds.test.js fails if these fall out of sync with public/app.js.

const BUILTIN_SCENARIOS = {
${entries}
};

const BUILTIN_HASHES = new Set(
  Object.values(BUILTIN_SCENARIOS).flatMap((stories) => stories.map((s) => s.hash)),
);

function isBuiltinWorld(worldId) {
  return typeof worldId === "string" && Object.hasOwn(BUILTIN_SCENARIOS, worldId);
}

// True only when worldId names a built-in world AND the scenario is one of that
// world's stories. Both halves matter: the world id alone is client-supplied and
// says nothing about the premise travelling with it.
function isBuiltinScenario(worldId, scenarioHash) {
  if (!isBuiltinWorld(worldId)) return false;
  return BUILTIN_SCENARIOS[worldId].some((s) => s.hash === scenarioHash);
}

module.exports = {
  BUILTIN_SCENARIOS,
  BUILTIN_HASHES,
  isBuiltinWorld,
  isBuiltinScenario,
};
`;
}

if (require.main === module) {
  const source = fs.readFileSync(APP_JS, "utf8");
  const catalogue = extractCatalogue(source);
  const worlds = extractBuiltins(source);
  fs.writeFileSync(OUT, render(worlds));
  fs.writeFileSync(CATALOG_OUT, `${JSON.stringify(catalogue, null, 2)}\n`);
  const count = Object.values(worlds).reduce((n, s) => n + s.length, 0);
  console.log(`wrote lib/worlds.js and lib/builtin-catalog.json — ${Object.keys(worlds).length} worlds, ${count} scenarios`);
}

module.exports = { extractBuiltins, extractCatalogue, scenarioTriple, render };
